/* Generated by tools/generate_codex_status_assets.py. */
#pragma once

#include <lvgl.h>

extern const lv_image_dsc_t codex_status_work;
extern const lv_image_dsc_t codex_status_wait;
extern const lv_image_dsc_t codex_status_done;
extern const lv_image_dsc_t codex_status_fail;
extern const lv_image_dsc_t codex_status_off;
