#!/usr/bin/env python3

from pathlib import Path

from PIL import Image, ImageDraw


WIDTH = 50
HEIGHT = 18
SCALE = 8
STATES = (
    ("work", "WORK"),
    ("wait", "WAIT"),
    ("done", "DONE"),
    ("fail", "FAIL"),
    ("off", "OFF"),
)

GLYPHS = {
    "A": ("01110", "10001", "10001", "11111", "10001", "10001", "10001"),
    "D": ("11110", "10001", "10001", "10001", "10001", "10001", "11110"),
    "E": ("11111", "10000", "10000", "11110", "10000", "10000", "11111"),
    "F": ("11111", "10000", "10000", "11110", "10000", "10000", "10000"),
    "I": ("11111", "00100", "00100", "00100", "00100", "00100", "11111"),
    "K": ("10001", "10010", "10100", "11000", "10100", "10010", "10001"),
    "L": ("10000", "10000", "10000", "10000", "10000", "10000", "11111"),
    "N": ("10001", "11001", "10101", "10101", "10101", "10011", "10001"),
    "O": ("01110", "10001", "10001", "10001", "10001", "10001", "01110"),
    "R": ("11110", "10001", "10001", "11110", "10100", "10010", "10001"),
    "T": ("11111", "00100", "00100", "00100", "00100", "00100", "00100"),
    "W": ("10001", "10001", "10001", "10101", "10101", "10101", "01010"),
}


def pixel(draw: ImageDraw.ImageDraw, x: int, y: int) -> None:
    draw.point((x, y), fill=0)


def line(draw: ImageDraw.ImageDraw, points: list[tuple[int, int]]) -> None:
    draw.line(points, fill=0, width=1)


def draw_robot(draw: ImageDraw.ImageDraw, state: str) -> None:
    # Keep the complete icon inside the 18 px-high central widget area.
    line(draw, [(4, 3), (4, 16), (15, 16), (15, 3), (4, 3)])
    line(draw, [(7, 2), (12, 2)])
    pixel(draw, 9, 1)
    pixel(draw, 6, 7)
    pixel(draw, 13, 7)

    if state == "work":
        line(draw, [(7, 12), (12, 12)])
        pixel(draw, 1, 5)
        pixel(draw, 1, 8)
        pixel(draw, 1, 11)
    elif state == "wait":
        line(draw, [(7, 12), (12, 12)])
        pixel(draw, 18, 5)
        pixel(draw, 18, 8)
        pixel(draw, 18, 11)
    elif state == "done":
        line(draw, [(7, 11), (9, 13), (13, 9)])
    elif state == "fail":
        line(draw, [(7, 10), (12, 14)])
        line(draw, [(12, 10), (7, 14)])
    elif state == "off":
        line(draw, [(6, 7), (7, 8)])
        line(draw, [(12, 8), (13, 7)])
        pixel(draw, 16, 3)
        line(draw, [(17, 1), (19, 1), (17, 3), (19, 3)])


def draw_text(draw: ImageDraw.ImageDraw, text: str, x: int, y: int) -> None:
    for char in text:
        glyph = GLYPHS[char]
        for row, bits in enumerate(glyph):
            for col, bit in enumerate(bits):
                if bit == "1":
                    pixel(draw, x + col, y + row)
        x += 6


def make_frame(state: str, label: str) -> Image.Image:
    image = Image.new("1", (WIDTH, HEIGHT), 1)
    draw = ImageDraw.Draw(image)
    draw_robot(draw, state)
    draw_text(draw, label, 23, 6)
    return image


def lvgl_bytes(image: Image.Image) -> list[int]:
    stride = (WIDTH + 7) // 8
    data = [0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF]
    for y in range(HEIGHT):
        row = [0] * stride
        for x in range(WIDTH):
            if image.getpixel((x, y)) == 0:
                row[x // 8] |= 0x80 >> (x % 8)
        data.extend(row)
    return data


def format_bytes(data: list[int]) -> str:
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def write_lvgl_sources(root: Path, frames: dict[str, Image.Image]) -> None:
    target = root / "boards" / "shields" / "tom_oled" / "widgets" / "assets"
    target.mkdir(parents=True, exist_ok=True)

    header = """/* Generated by tools/generate_codex_status_assets.py. */
#pragma once

#include <lvgl.h>

extern const lv_img_dsc_t codex_status_work;
extern const lv_img_dsc_t codex_status_wait;
extern const lv_img_dsc_t codex_status_done;
extern const lv_img_dsc_t codex_status_fail;
extern const lv_img_dsc_t codex_status_off;
"""
    (target / "codex_status_images.h").write_text(header)

    sections = [
        "/* Generated by tools/generate_codex_status_assets.py. */",
        '#include "codex_status_images.h"',
        "",
    ]
    for state, _ in STATES:
        data = lvgl_bytes(frames[state])
        sections.extend(
            [
                f"static const uint8_t codex_status_{state}_map[] = {{",
                format_bytes(data),
                "};",
                "",
                f"const lv_img_dsc_t codex_status_{state} = {{",
                "    .header.cf = LV_IMG_CF_INDEXED_1BIT,",
                "    .header.always_zero = 0,",
                "    .header.reserved = 0,",
                f"    .header.w = {WIDTH},",
                f"    .header.h = {HEIGHT},",
                f"    .data_size = {len(data)},",
                f"    .data = codex_status_{state}_map,",
                "};",
                "",
            ]
        )
    (target / "codex_status_images.c").write_text("\n".join(sections))


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out_dir = root / "assets" / "codex_status"
    out_dir.mkdir(parents=True, exist_ok=True)

    frames = {}
    for state, label in STATES:
        frame = make_frame(state, label)
        frame.save(out_dir / f"codex_{state}.png")
        frames[state] = frame

    gap = 2
    sheet = Image.new("1", (WIDTH, HEIGHT * len(frames) + gap * (len(frames) - 1)), 1)
    for index, (state, _) in enumerate(STATES):
        frame = frames[state]
        sheet.paste(frame, (0, index * (HEIGHT + gap)))

    preview = sheet.resize((WIDTH * SCALE, sheet.height * SCALE), Image.Resampling.NEAREST)
    preview.save(out_dir / "codex_status_preview.png")
    write_lvgl_sources(root, frames)


if __name__ == "__main__":
    main()
